import { Injectable } from '@angular/core';
import type { TemplateRecord } from '../../../core/models/graph.models';

const STARTER_TEMPLATES: TemplateRecord[] = [
  {
    id: 'template-2wd-buggy-carpet-baseline',
    name: '2WD Buggy Carpet Baseline',
    description:
      'A baseline tuning map with common setup levers, symptom anchors, and high-grip carpet context.',
    createdAt: '2026-03-14T00:00:00.000Z',
    updatedAt: '2026-03-14T00:00:00.000Z',
    graphData: {
      graph: {
        name: '2WD Buggy Carpet Baseline',
        chassis: 'Associated B7',
        classType: '2wd-buggy',
        surface: 'carpet',
        notes: 'Baseline starter map for high-grip carpet tuning sessions.',
      },
      nodes: [
        {
          id: 'condition-high-grip',
          type: 'condition',
          subtype: 'surface',
          title: 'High-grip carpet',
          description: 'Primary race condition for the baseline graph.',
          tags: ['carpet', 'baseline'],
          phaseTags: ['entry', 'mid', 'exit'],
          confidence: 'high',
          position: { x: 80, y: 160 },
          data: { label: 'High-grip carpet', category: 'Condition' },
        },
        {
          id: 'setup-rear-oil',
          type: 'setup',
          subtype: 'rear-oil',
          title: 'Rear oil 32.5wt',
          description: 'Rear shock package for planted rotation.',
          tags: ['shocks'],
          phaseTags: ['mid', 'exit'],
          confidence: 'medium',
          position: { x: 340, y: 80 },
          data: { label: 'Rear oil 32.5wt', category: 'Setup' },
        },
        {
          id: 'symptom-lazy-rotation',
          type: 'symptom',
          subtype: 'rotation',
          title: 'Lazy rotation',
          description: 'Car is not rotating quickly enough at corner entry.',
          tags: ['rotation'],
          phaseTags: ['entry', 'mid'],
          confidence: 'high',
          position: { x: 340, y: 260 },
          data: { label: 'Lazy rotation', category: 'Symptom' },
        },
        {
          id: 'experiment-camber-link',
          type: 'experiment',
          subtype: 'camber-link',
          title: 'Raise rear camber link',
          description: 'Test more rotation without losing exit security.',
          tags: ['test'],
          phaseTags: ['entry'],
          confidence: 'medium',
          position: { x: 620, y: 260 },
          data: { label: 'Raise rear camber link', category: 'Experiment' },
        },
        {
          id: 'outcome-more-steering',
          type: 'outcome',
          subtype: 'steering',
          title: 'More steering on entry',
          description: 'Desired outcome from setup and experiment changes.',
          tags: ['steering'],
          phaseTags: ['entry'],
          confidence: 'medium',
          position: { x: 900, y: 160 },
          data: { label: 'More steering on entry', category: 'Outcome' },
        },
      ],
      edges: [
        {
          id: 'edge-condition-setup',
          sourceNodeId: 'condition-high-grip',
          targetNodeId: 'setup-rear-oil',
          relationshipType: 'influences',
          label: 'influences',
          description: 'Surface grip changes shock package needs.',
          confidence: 'high',
          phaseTags: ['entry', 'mid', 'exit'],
          evidenceType: 'theory',
        },
        {
          id: 'edge-setup-symptom',
          sourceNodeId: 'setup-rear-oil',
          targetNodeId: 'symptom-lazy-rotation',
          relationshipType: 'can reduce',
          label: 'can reduce',
          description: 'Rear damping can free the car up on entry.',
          confidence: 'medium',
          phaseTags: ['entry', 'mid'],
          evidenceType: 'theory',
        },
        {
          id: 'edge-symptom-experiment',
          sourceNodeId: 'symptom-lazy-rotation',
          targetNodeId: 'experiment-camber-link',
          relationshipType: 'tested',
          label: 'tested',
          description: 'Experiment logged to chase rotation.',
          confidence: 'medium',
          phaseTags: ['entry'],
          evidenceType: 'observed',
        },
        {
          id: 'edge-experiment-outcome',
          sourceNodeId: 'experiment-camber-link',
          targetNodeId: 'outcome-more-steering',
          relationshipType: 'observed',
          label: 'observed',
          description: 'Observed improvement in steering response.',
          confidence: 'medium',
          phaseTags: ['entry'],
          evidenceType: 'observed',
        },
      ],
    },
  },
  {
    id: 'template-symptom-driven-troubleshooting',
    name: 'Symptom-Driven Troubleshooting Map',
    description:
      'A symptom-first map for experiments, observed results, and common 2WD carpet handling issues.',
    createdAt: '2026-03-14T00:00:00.000Z',
    updatedAt: '2026-03-14T00:00:00.000Z',
    graphData: {
      graph: {
        name: 'Symptom-Driven Troubleshooting Map',
        chassis: 'Associated B7',
        classType: '2wd-buggy',
        surface: 'carpet',
        notes: 'Symptom-first starter map for guided troubleshooting.',
      },
      nodes: [
        {
          id: 'symptom-entry-push',
          type: 'symptom',
          subtype: 'entry-push',
          title: 'Entry push',
          description: 'Car resists initial turn-in on carpet.',
          tags: ['steering'],
          phaseTags: ['entry', 'braking'],
          confidence: 'high',
          position: { x: 120, y: 120 },
          data: { label: 'Entry push', category: 'Symptom' },
        },
        {
          id: 'symptom-exit-instability',
          type: 'symptom',
          subtype: 'exit-instability',
          title: 'Exit instability',
          description: 'Rear of the car steps out when throttle is applied.',
          tags: ['rear-grip'],
          phaseTags: ['exit', 'on-power'],
          confidence: 'medium',
          position: { x: 120, y: 320 },
          data: { label: 'Exit instability', category: 'Symptom' },
        },
        {
          id: 'experiment-softer-insert',
          type: 'experiment',
          subtype: 'tire-insert',
          title: 'Swap to softer insert',
          description: 'Try calmer rear response on power.',
          tags: ['tires'],
          phaseTags: ['exit', 'on-power'],
          confidence: 'medium',
          position: { x: 420, y: 320 },
          data: { label: 'Swap to softer insert', category: 'Experiment' },
        },
        {
          id: 'setup-rear-toe',
          type: 'setup',
          subtype: 'rear-toe',
          title: 'Rear toe +3.0',
          description: 'Rear toe setting that can calm exit behavior.',
          tags: ['rear-grip'],
          phaseTags: ['exit'],
          confidence: 'medium',
          position: { x: 420, y: 120 },
          data: { label: 'Rear toe +3.0', category: 'Setup' },
        },
        {
          id: 'outcome-better-forward-bite',
          type: 'outcome',
          subtype: 'forward-bite',
          title: 'Better forward bite',
          description: 'More secure power-down and acceleration.',
          tags: ['traction'],
          phaseTags: ['exit', 'on-power'],
          confidence: 'medium',
          position: { x: 760, y: 240 },
          data: { label: 'Better forward bite', category: 'Outcome' },
        },
      ],
      edges: [
        {
          id: 'edge-setup-entry-push',
          sourceNodeId: 'setup-rear-toe',
          targetNodeId: 'symptom-entry-push',
          relationshipType: 'tradeoff',
          label: 'tradeoff',
          description: 'Rear toe can stabilize exit but hurt turn-in.',
          confidence: 'medium',
          phaseTags: ['entry', 'exit'],
          evidenceType: 'theory',
        },
        {
          id: 'edge-symptom-experiment-soft-insert',
          sourceNodeId: 'symptom-exit-instability',
          targetNodeId: 'experiment-softer-insert',
          relationshipType: 'tested',
          label: 'tested',
          description: 'Logged experiment for exit stability.',
          confidence: 'medium',
          phaseTags: ['exit', 'on-power'],
          evidenceType: 'observed',
        },
        {
          id: 'edge-experiment-outcome-forward-bite',
          sourceNodeId: 'experiment-softer-insert',
          targetNodeId: 'outcome-better-forward-bite',
          relationshipType: 'observed',
          label: 'observed',
          description: 'Observed calmer rear and improved drive.',
          confidence: 'medium',
          phaseTags: ['exit', 'on-power'],
          evidenceType: 'observed',
        },
      ],
    },
  },
];

@Injectable({
  providedIn: 'root',
})
export class TemplatesCatalog {
  all(): TemplateRecord[] {
    return STARTER_TEMPLATES.map(
      (template) => JSON.parse(JSON.stringify(template)) as TemplateRecord,
    );
  }

  getById(templateId: string): TemplateRecord | undefined {
    return this.all().find((template) => template.id === templateId);
  }
}
